"""LeRobot-style metadata bridge for mock teleop review episodes."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from robotics_reviewkit.episode import NormalizedEpisode
from robotics_reviewkit.episode import duration_seconds
from robotics_reviewkit.episode import normalize_episodes
from robotics_reviewkit.episode import sensor_names
from robotics_reviewkit.episode import training_ready

METADATA_ONLY_LIMITATIONS = [
    "Exports reviewed episode metadata only.",
    "Does not generate LeRobot parquet shards, tensors, images, videos, or action arrays.",
    "Mock examples are tutorial data and are not human-validated training datasets.",
]


def _json_dump(path: Path, payload: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def _tasks(episodes: list[NormalizedEpisode]) -> list[dict[str, Any]]:
    task_order: dict[str, dict[str, Any]] = {}
    for episode in episodes:
        if episode.task_id not in task_order:
            task_order[episode.task_id] = {
                "task_index": len(task_order),
                "task_id": episode.task_id,
                "task_name": episode.task_name,
            }
    return list(task_order.values())


def _episode_payload(
    episode: NormalizedEpisode,
    episode_index: int,
    task_index: int,
) -> dict[str, Any]:
    raw = episode.raw
    sensors = sensor_names(raw)
    readiness = raw.get("training_readiness")
    if readiness is None and isinstance(raw.get("review"), dict):
        readiness = raw["review"].get("training_readiness")

    return {
        "episode_id": episode.episode_id,
        "episode_index": episode_index,
        "task_index": task_index,
        "task_id": episode.task_id,
        "task_name": episode.task_name,
        "embodiment": {
            "id": episode.embodiment_id,
            "name": episode.embodiment_name,
        },
        "duration_seconds": duration_seconds(raw),
        "frame_count": None,
        "fps": None,
        "split": "train" if training_ready(episode.readiness_state) else "review",
        "metadata_only": True,
        "observations": {
            "placeholder": True,
            "available_sensor_metadata": sensors,
            "note": "Sensor names and QA metadata are exported; image/video/tensor observations are not generated.",
        },
        "actions": {
            "placeholder": True,
            "note": "Teleop action arrays are not generated by this metadata bridge.",
        },
        "annotations": {
            "segments": raw.get("segments") or [],
            "interventions": raw.get("interventions") or [],
            "failure_modes": raw.get("failure_modes") or [],
            "sensor_qa": raw.get("sensor_qa") or {},
            "review": raw.get("review") or {},
            "training_readiness": readiness,
        },
        "source_metadata": {
            "schema": raw.get("schema", "teleop_review_schema"),
            "schema_version": raw.get("schema_version"),
            "mock_data": bool(raw.get("mock_data", True)),
        },
    }


def build_lerobot_metadata_export(
    payload: Any,
    *,
    dataset_name: str = "auraone_mock_lerobot_metadata",
) -> dict[str, Any]:
    """Build a LeRobot-style metadata skeleton from mock teleop episodes."""

    episodes = normalize_episodes(payload)
    tasks = _tasks(episodes)
    task_index_by_id = {task["task_id"]: task["task_index"] for task in tasks}
    episode_payloads = [
        _episode_payload(episode, index, task_index_by_id[episode.task_id])
        for index, episode in enumerate(episodes)
    ]

    return {
        "export_type": "lerobot_metadata_bridge",
        "format": "LeRobot-style metadata JSON",
        "compatibility": "metadata_only",
        "dataset": {
            "name": dataset_name,
            "generated_by": "auraone-robotics-reviewkit",
            "episode_count": len(episode_payloads),
            "task_count": len(tasks),
            "mock_data": True,
        },
        "tasks": tasks,
        "episodes": episode_payloads,
        "limitations": METADATA_ONLY_LIMITATIONS,
    }


def write_lerobot_metadata_export(
    payload: Any,
    output_dir: str | Path,
    *,
    dataset_name: str = "auraone_mock_lerobot_metadata",
) -> dict[str, Any]:
    """Write a deterministic LeRobot-style metadata directory."""

    output = Path(output_dir)
    export = build_lerobot_metadata_export(payload, dataset_name=dataset_name)

    _json_dump(output / "manifest.json", export)
    _json_dump(output / "meta" / "info.json", export["dataset"] | {"compatibility": export["compatibility"]})
    tasks_path = output / "meta" / "tasks.jsonl"
    tasks_path.parent.mkdir(parents=True, exist_ok=True)
    tasks_path.write_text(
        "".join(json.dumps(task, sort_keys=True) + "\n" for task in export["tasks"]),
        encoding="utf-8",
    )
    for episode in export["episodes"]:
        _json_dump(output / "episodes" / f"{episode['episode_id']}.json", episode)

    return export
